### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by umairsali07** [Vetchems/sd-civitai-browser#3]
File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/WebUI/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai-api.py", line 199, in save_text_file
    path_to_new_file = os.path.join(model_folder, file_name.replace(".ckpt",".txt").replace(".safetensors",".txt").replace(".pt",".txt"))
AttributeError: 'list' object has no attribute 'replace'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/gradio/routes.py", line 337, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 1015, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.8/dist-packages/gradio/blocks.py", line 833, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/dist-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/dist-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/content/gdrive/MyDrive/WebUI/stable-diffusion-webui/extensions/sd-civitai-browser/scripts/civitai-api.py", line 150, in download_file_thread
    path_to_new_file = os.path.join(model_folder, file_name)
  File "/usr/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'list'

**Comment by thetrebor** [comment]
this should be fixed with the latest PR

**Comment by wilzamguerrero** [comment]
not working what can we do
not preview
not download

**Comment by thetrebor** [comment]
did you try my PR?

**Comment by wilzamguerrero** [comment]
What is PR sorry

**Comment by thetrebor** [comment]
Check out my version of the repository or respectfully and politely ask the
author of this one to merge my fixes.  If you’re not a developer you’ll
need to google a bit.  Good luck

**Comment by wilzamguerrero** [comment]
Thank you so much
